name: Generate Doxygen Documentation

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-upload-docs:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install Doxygen
      run: |
        sudo apt-get update
        sudo apt-get install -y doxygen graphviz

    - name: Run Doxygen
      run: |
        doxygen Doxyfile

    - name: Upload Doxygen Artifact
      uses: actions/upload-artifact@v4
      with:
        name: doxygen-documentation
        path: html/
        retention-days: 30